title: "AI for Software Development"
description: "Exploring the role of AI and LLMs in transforming software development workflows"
author: "Charles Norris"
baseurl: "/"
url: "https://Charlesnorris509.github.io"  # Change this to your GitHub Pages URL

# Enable the blog feature with Jekyll
theme: jekyll-skin  # You can change this to any theme you'd like

markdown: kramdown  # This sets the Markdown engine for parsing Markdown files

plugins:
  - jekyll-feed  # Enables RSS feed (optional but useful for blogs)

# Permalinks for posts (optional, you can customize how URLs appear)
permalink: /:year/:month/:day/:title/

# URL structure for posts
collections:
  posts:
    output: true  # Tells Jekyll to process posts and output them as static files

# Exclude certain files/folders from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - _config.yml
  - _drafts

# Optional: Custom CSS (link to style.css if you have one)
css:
  - "/style.css"
